// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjmyyaqjowcnhuqftikp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqbXl5YXFqb3djbmh1cWZ0aWtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxODUxODUsImV4cCI6MjA4NDc2MTE4NX0.RgmL14MxtBS2t-MB-l-iAGAN2hqhXttxquXQ71mGnik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});